# Generated by Django 5.1.2 on 2024-12-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0032_customuser_childprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ChildProfile',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
